### ISSUE TITLE
Problems with building.

### ISSUE THREAD

**Issue by andriiqx** [Groovin-Dev/TeamsExpansion#3]
I builded plugin as you said: i had cloned repo, and then run gradlew shadowJar 

but, in minecraft i get this: (1.20.1 spigot)

![Screenshot_6896](https://github.com/Groovin-Dev/TeamsExpansion/assets/116912308/a3550d34-b582-4fe6-80f9-37bea2635daa)

**Comment by Groovin-Dev** [comment]
I couldn't replicate this. What version of PlaceholderAPI are you using?
![image](https://github.com/Groovin-Dev/TeamsExpansion/assets/56172528/f9822f84-b1a5-4600-a0a2-bd0033c1ab58)
